apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-eks-lab-static
data:
  index.html: |
    <html>
      <head><title>Hello EKS</title></head>
      <body style="font-family: Arial;">
        <h1>Hello from EKS + nginx!</h1>
        <p>If you see this page, ConfigMap mount works.</p>
      </body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-eks-lab-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-eks-lab
  template:
    metadata:
      labels:
        app: hello-eks-lab
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
          volumeMounts:
            - name: site
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: site
          configMap:
            name: hello-eks-lab-static

---
apiVersion: v1
kind: Service
metadata:
  name: hello-eks-lab
spec:
  type: LoadBalancer
  selector:
    app: hello-eks-lab
  ports:
    - port: 80
      targetPort: 80
