ufw_allow_rules:
  - { port: "22", proto: "tcp" }
  - { port: "80", proto: "tcp" }
  - { port: "443", proto: "tcp" }

nginx_listen_port: 80
nginx_server_name: "_"
nginx_custom_directory: /var/www/web_domain

secrets_manager_name: "prod/test"
secrets_manager_region: "eu-north-1"

secrets_env_dir: "/opt/test"
secrets_env_file: "/opt/test/.env"

secrets_env_mapping:
  DB_USER: "db_user"
  DB_PASS: "db_pass"